import { Inter } from 'next/font/google'
import './globals.css'
import NavbarHome from './componentes/NavBarHome'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <div>
          <NavbarHome></NavbarHome>
          {children}
        </div>
      </body>
    </html>
  )
}
